# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

linters:
  enable-all: true
  disable:
    - containedctx # Silly.
    - contextcheck # Inaccurate.
    - cyclop
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errchkjson # Redundant.
    - execinquery
    - exhaustruct # Pass.
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - godot
    - godox
    - gomnd
    - inamedparam
    - interfacebloat # nope
    - ireturn # Noisy.
    - lll
    - mnd
    - musttag # issues errors in the stdlib
    - nestif
    - nlreturn
    - nonamedreturns # No.
    - paralleltest
    - revive # redundant
    - sqlclosecheck
    - stylecheck
    - tagalign
    - tagliatelle
    - testpackage
    - thelper # Broken and racy.
    - unparam
    - varnamelen # Silly.
    - wsl

    # - staticcheck

linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - github.com/hortbot/hortbot/internal/pkg/apiclient.NewStatusError(
      - github.com/hortbot/hortbot/internal/pkg/apiclient.WrapRequestErr(
    ignorePackageGlobs:
      - context
      - github.com/hortbot/hortbot/internal/birc/breq
      - github.com/hortbot/hortbot/internal/pkg/errgroupx
      - github.com/hortbot/hortbot/internal/db/models # TODO
      - github.com/hortbot/hortbot/internal/db/modelsx # TODO
      - github.com/hortbot/hortbot/internal/db/redis # TODO
      - github.com/hortbot/hortbot/internal/pkg/wqueue
      - github.com/hortbot/hortbot/internal/pkg/repeat
      - github.com/hortbot/hortbot/internal/pkg/dbx
      - github.com/jarcoal/httpmock
      - github.com/redis/go-redis/v9 # TODO

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude:
    - "^could not import"
    - "^: #"
    - "imported and not used$"
