linters:
  enable-all: true
  disable:
    # https://github.com/golangci/golangci-lint/issues/484
    - containedctx # Silly.
    - contextcheck # Inaccurate.
    - cyclop
    - deadcode # dead
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errchkjson # Redundant.
    - execinquery
    - exhaustive # Breaks on enum values exported from test packages.
    - exhaustivestruct
    - exhaustruct # Pass.
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - godot
    - godox
    - gofumpt
    - golint # Deprecated
    - gomnd
    - govet
    - ifshort # Inaccurate.
    - inamedparam
    - interfacebloat # nope
    - interfacer
    - ireturn # Noisy.
    - lll
    - maligned
    - mnd
    - musttag # issues errors in the stdlib
    - nestif
    - nlreturn
    - nonamedreturns # No.
    - nosnakecase # dead
    - paralleltest
    - revive # redundant
    - scopelint # Deprecated
    - sqlclosecheck # incorrect
    - structcheck # dead
    - stylecheck
    - tagalign
    - tagliatelle
    - testpackage
    - thelper # Broken and racy.
    - unparam
    - unused
    - varcheck # dead
    - varnamelen # Silly.
    - wastedassign # Inaccurate.
    - wrapcheck
    - wsl

    # - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
