linters:
  enable-all: true
  disable:
    # https://github.com/golangci/golangci-lint/issues/484
    - containedctx # Silly.
    - contextcheck # Inaccurate.
    - cyclop
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errchkjson # Redundant.
    - execinquery
    - exhaustruct # Pass.
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - godot
    - godox
    - gomnd
    - inamedparam
    - interfacebloat # nope
    - ireturn # Noisy.
    - lll
    - mnd
    - musttag # issues errors in the stdlib
    - nestif
    - nlreturn
    - nonamedreturns # No.
    - paralleltest
    - revive # redundant
    - sqlclosecheck
    - stylecheck
    - tagalign
    - tagliatelle
    - testpackage
    - thelper # Broken and racy.
    - unparam
    - varnamelen # Silly.
    - wrapcheck
    - wsl

    # - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
