version: "2"
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errchkjson
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - godot
    - godox
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - musttag
    - nestif
    - nlreturn
    - nolintlint
    - nonamedreturns
    - revive
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testpackage
    - thelper
    - unparam
    - varnamelen
    - wsl
    - funcorder
    - gosmopolitan
    - wsl_v5
    - noinlineerr
    - embeddedstructfieldcheck
    - unqueryvet
  settings:
    forbidigo:
      forbid:
        - pattern: ^http\.NewRequest$
        - pattern: ^http\.NewRequestWithContext$
        - pattern: ^http\.(Client\.)?Do$
        - pattern: ^http\.(Client\.)?Get$
        - pattern: ^http\.(Client\.)?Head$
        - pattern: ^http\.(Client\.)?Post$
        - pattern: ^http\.(Client\.)?PostForm$
      analyze-types: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - github.com/hortbot/hortbot/internal/pkg/apiclient.NewStatusError(
        - github.com/hortbot/hortbot/internal/pkg/apiclient.NewNonStatusError(
        - github.com/hortbot/hortbot/internal/pkg/apiclient.WrapRequestErr(
      ignore-package-globs:
        - context
        - github.com/hortbot/hortbot/internal/birc/breq
        - github.com/hortbot/hortbot/internal/pkg/dbx
        - github.com/hortbot/hortbot/internal/pkg/errgroupx
        - github.com/hortbot/hortbot/internal/pkg/repeat
        - github.com/hortbot/hortbot/internal/pkg/wqueue
        - github.com/jarcoal/httpmock
        - github.com/redis/go-redis/v9
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: ^could not import
      - path: (.+)\.go$
        text: '^: #'
      - path: (.+)\.go$
        text: imported and not used$
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
