# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

linters:
  enable-all: true
  disable:
    - containedctx # Silly.
    - contextcheck # Inaccurate.
    - cyclop
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errchkjson # Redundant.
    - execinquery
    - exhaustruct # Pass.
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - godot
    - godox
    - gomnd
    - inamedparam
    - interfacebloat # nope
    - ireturn # Noisy.
    - lll
    - mnd
    - musttag # issues errors in the stdlib
    - nestif
    - nlreturn
    - nonamedreturns # No.
    - paralleltest
    - revive # redundant
    - sqlclosecheck
    - stylecheck
    - tagalign
    - tagliatelle
    - testpackage
    - thelper # Broken and racy.
    - unparam
    - varnamelen # Silly.
    - wrapcheck
    - wsl

    # - staticcheck

# linters-settings:
#   wrapcheck:
#     ignorePackageGlobs:
#       - context
#       - github.com/hortbot/hortbot/internal/pkg/errgroupx

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude:
    - "^could not import"
    - "^: #"
    - "imported and not used$"
