// Code generated by "esc -o=esc/esc.go -pkg=esc -ignore=esc -include=\.sql$ -private -modtime=0 ."; DO NOT EDIT.

package esc

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/20190504194418_initial_schema.down.sql": {
		name:    "20190504194418_initial_schema.down.sql",
		local:   "20190504194418_initial_schema.down.sql",
		size:    283,
		modtime: 0,
		compressed: `
H4sIAAAAAAAC/1zPwW7DIAwG4DtP4QfYG+SUpmxCWtdqyWE7IQqegupABiZ7/R1Cqig3/9/B9n+Sb+qj
EeL8eb3B0J7eJahXkF+qH3oBAGBHEwJSfllTyRwnbeM0meAq/pbIWGdTOCacyW+wmOTNnbbIf57tqDk+
MFS6U7QPdLpkTNuZdb8mn/lAPvzESglnNIzu8E62I7pCOxdd23ftWT57ft92NcFYizlrwgWpEaK7Xi5q
aMR/AAAA//955cCYGwEAAA==
`,
	},

	"/20190504194418_initial_schema.up.sql": {
		name:    "20190504194418_initial_schema.up.sql",
		local:   "20190504194418_initial_schema.up.sql",
		size:    7119,
		modtime: 0,
		compressed: `
H4sIAAAAAAAC/+xYS28bNxC+61fMzTFqB/Y5SAHZZhIh9jqVZKRGURDU7kjLmo8NybWlFv3vBfch7YMr
OS2CNnB98orDGc583zzI01OYp9zCkgsEbsHmi98wduA0xClTK4RcOS7ApQhLbqwDg0xAgpnQG4nKgV4W
iwvtXo9OT+FKg9JeSmxAK79kEWycomQg+cowx7WyYFAyrrhaQayV5dZ5VbUpbr0midayFULKLCwQld+j
HzF5PRpdkPeT6M1oNLqckvGcwPz+EwEWx2gtFfiIAsYzINHdDbwaAQAc4SOajVZ4dFJ+23xhY8MXaOpf
pE7QMKe3PyyMZknMrNvJsERydTQ6bloeX1yTIlQKha3M8QQWfMWVg/ckItPxnFzBxT1ckXfju+u5P9vk
ikTzyfwePk0nN+PpPXwk96WR2CBzmFDmwHGJ1jGZud+3e6Pbz6+OIbqdQ3R3fV1uybPka7aUeywaujtn
vQp30eSnO1LqVUwiOFy7jr2FdnRojcWOP3o2aIFMdRYzg0u+DqrMhUBXrFQH9Hi0Ie14wFdKG0yKPb/8
uvX26I8/jzrK49w6Lal+Umjs8+WlTr5C2uAqF+yg/nKL1iLRTwq4cqUSwayjsZaSqR6Onc2F6FKGopgx
Y5FudO7yxRAGuHaGUcGX6OFvYl+uG7ZcCqSo2EJgElBSSNlU5yKhVdIM2Uq4zQTb0CdmfKrboSMVtg5J
+ZDo3NEkL2tI4OyVoiUXziM9cPZymQquHoZsZWgkdz6nSqnDLPAFhUq2KTYcsByzbMhwQ4JKrmicekr1
PW3KZWhiVM6Xyv2ChUJvuy3WlEOpHR44XClDJVsP26tkLFcrgQfCYTdyocUBo5XQs5ytZb2/tfJhlyXu
tyzZmgpUK5fuUbLw9T+hWWqYPRS/tizNmHNo1LMKx+UHcvkRXg2gf0HmnwmJ4AyYSuD87Oz4JLArEMkD
G3uZ9+NbODsu2mDVBSfRFfl52wVp1VwoT9Z+Bth1x2oh0EDLIlpVwO+oj1a+NVrplLwjUxJdklnDcZ70
dtbjTauOB4LajgzdGSzCexv1Y7cT6Qf6S14k+AuIr8ploEQU/nd7584hbUJ9FRMeWCmWynmpGfMTbzmQ
HWXkm/ipXNYY1rB01fTwY7nTBjPBXzKIzvDVCoNQacNXdUmtxsliqkGbaWWDI2usc+VCtf1bM6KBZSCt
W0i3UnpQSYNQrd0+iuPZZeMAJZkemeF+YnoZVBq4sTwykePzkWQSA1BuI9nKbyaxxqMR6p66XpK7J+7i
lDr9gOo7wqY69p5bZXVFLC51hXchQIoF6jZZEC6DS4M2Hd6O64ybTfAG1cetFWm6daBGrQPEdr0P2ULo
+AGTYvT5FyB7VvxHvQJQ3zgFt+5FFAHuUO6ftEOvO1WUuFrqF1oqW+9CrVeZgSeaXWPtcPHkH7TW9qQ7
4Fh3Gvb+NU/f5PyAinZWNBWU16LbaDafjifRHOL0geaKf8mL15TqvlQI+b/df8XX5XhG4PMHEgUcmczK
OM8/FPcwcj0jcA6okuOWjh9aWjqePEPHMbyF8+IrdH9r8nyokXWS4XAzM5iVdH8hl7smx3yQ9nOsCmNT
RZtsww9xxQsbCrYJTMjV5ZImfLmsrdeunndkq7fHYK7+nWTtE6tHgcC4G6DJ8NAbUNiO+D6tbck+YW2c
YpKL/xn7TRgbG60orjOD1nIdnOD+W+Tt0yHA3hBnhukbUhnmb1BviMC3NzeT+ZvRXwEAAP//RkuQH88b
AAA=
`,
	},

	"/": {
		name:  "/",
		local: `.`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	".": {
		_escData["/20190504194418_initial_schema.down.sql"],
		_escData["/20190504194418_initial_schema.up.sql"],
	},
}
