// Code generated by counterfeiter. DO NOT EDIT.
package urbanfakes

import (
	"context"
	"sync"

	"github.com/hortbot/hortbot/internal/pkg/apiclient/urban"
)

type FakeAPI struct {
	DefineStub        func(context.Context, string) (string, error)
	defineMutex       sync.RWMutex
	defineArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	defineReturns struct {
		result1 string
		result2 error
	}
	defineReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAPI) Define(arg1 context.Context, arg2 string) (string, error) {
	fake.defineMutex.Lock()
	ret, specificReturn := fake.defineReturnsOnCall[len(fake.defineArgsForCall)]
	fake.defineArgsForCall = append(fake.defineArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("Define", []interface{}{arg1, arg2})
	fake.defineMutex.Unlock()
	if fake.DefineStub != nil {
		return fake.DefineStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.defineReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAPI) DefineCallCount() int {
	fake.defineMutex.RLock()
	defer fake.defineMutex.RUnlock()
	return len(fake.defineArgsForCall)
}

func (fake *FakeAPI) DefineCalls(stub func(context.Context, string) (string, error)) {
	fake.defineMutex.Lock()
	defer fake.defineMutex.Unlock()
	fake.DefineStub = stub
}

func (fake *FakeAPI) DefineArgsForCall(i int) (context.Context, string) {
	fake.defineMutex.RLock()
	defer fake.defineMutex.RUnlock()
	argsForCall := fake.defineArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAPI) DefineReturns(result1 string, result2 error) {
	fake.defineMutex.Lock()
	defer fake.defineMutex.Unlock()
	fake.DefineStub = nil
	fake.defineReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) DefineReturnsOnCall(i int, result1 string, result2 error) {
	fake.defineMutex.Lock()
	defer fake.defineMutex.Unlock()
	fake.DefineStub = nil
	if fake.defineReturnsOnCall == nil {
		fake.defineReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.defineReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeAPI) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.defineMutex.RLock()
	defer fake.defineMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAPI) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ urban.API = new(FakeAPI)
