name: Setup Go and caches
description: Setup Go and build/module caches

inputs:
  go-version:
    description: "The Go version to download (if necessary) and use. Supports semver spec and ranges."
    default: "1.24" # Sync with README, go.mod, and docker-compose.yml.
  cache-name:
    description: "Name of the cache, for separate jobs which may use different modules/builds."
    default: "cache"

runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: ${{ inputs.go-version }}
        check-latest: true
        cache: false

    - name: Install Go
      # if: ${{ inputs.go-version }} != 'tip'
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: ${{ inputs.go-version }}
        check-latest: true
        cache: false

    # - name: Install Go tip
    #   if: ${{ inputs.go-version }} == 'tip'
    #   run: |
    #     git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
    #     cd $HOME/gotip/src
    #     ./make.bash
    #     ../bin/go version
    #     echo "GOROOT=$HOME/gotip" >> $GITHUB_ENV
    #     echo "$HOME/gotip/bin:$PATH" >> $GITHUB_PATH

    # https://github.com/mvdan/github-actions-golang
    - name: Cache Go modules
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ inputs.cache-name }}-modules-${{ inputs.go-version }}-${{ hashFiles('**/go.sum') }}

    - name: Cache go-build
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: |
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ inputs.cache-name }}-build-${{ inputs.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build-
