BEGIN;

DROP TABLE IF EXISTS scheduled_commands CASCADE;

DROP TABLE IF EXISTS repeated_commands CASCADE;

DROP TABLE IF EXISTS quotes CASCADE;

DROP TABLE IF EXISTS simple_commands CASCADE;

DROP TABLE IF EXISTS channels CASCADE;

DROP TYPE IF EXISTS access_level;

COMMIT;
