BEGIN;

DROP TABLE IF EXISTS link_permits CASCADE;

DROP TABLE IF EXISTS quotes CASCADE;

DROP TABLE IF EXISTS simple_commands CASCADE;

DROP TABLE IF EXISTS channels CASCADE;

DROP TYPE IF EXISTS access_level;

COMMIT;
