#!/bin/sh -e

# This script updates every requirement explicitly listed in a module's go.mod.
# This is intended to replace 'go get -d -t -u ./...', which strangely updates
# the dependencies of the dependencies of the listed packages (rather than just
# the dependencies themselves).

cd "${0%/*}/.."

module=$(go list -f '{{.Module.Path}}' .)

go mod tidy
go get -d -t $(go mod graph | grep "^$module" | cut -d ' ' -f 2 | sed 's/@.*/@upgrade/g')
go mod tidy
go mod download
