// Code generated by "stringer -type=accessLevel -trimprefix=level"; DO NOT EDIT.

package bot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[levelUnknown-0]
	_ = x[levelEveryone-1]
	_ = x[levelSubscriber-2]
	_ = x[levelVIP-3]
	_ = x[levelModerator-4]
	_ = x[levelBroadcaster-5]
	_ = x[levelAdmin-6]
	_ = x[levelSuperAdmin-7]
}

const _accessLevel_name = "UnknownEveryoneSubscriberVIPModeratorBroadcasterAdminSuperAdmin"

var _accessLevel_index = [...]uint8{0, 7, 15, 25, 28, 37, 48, 53, 63}

func (i accessLevel) String() string {
	if i < 0 || i >= accessLevel(len(_accessLevel_index)-1) {
		return "accessLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _accessLevel_name[_accessLevel_index[i]:_accessLevel_index[i+1]]
}
