// Code generated by "stringer -type=AccessLevel -trimprefix=AccessLevel"; DO NOT EDIT.

package bot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessLevelUnknown-0]
	_ = x[AccessLevelEveryone-1]
	_ = x[AccessLevelSubscriber-2]
	_ = x[AccessLevelVIP-3]
	_ = x[AccessLevelModerator-4]
	_ = x[AccessLevelBroadcaster-5]
	_ = x[AccessLevelAdmin-6]
	_ = x[AccessLevelSuperAdmin-7]
}

const _AccessLevel_name = "UnknownEveryoneSubscriberVIPModeratorBroadcasterAdminSuperAdmin"

var _AccessLevel_index = [...]uint8{0, 7, 15, 25, 28, 37, 48, 53, 63}

func (i AccessLevel) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AccessLevel_index)-1 {
		return "AccessLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccessLevel_name[_AccessLevel_index[idx]:_AccessLevel_index[idx+1]]
}
