// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Channels       string
	LinkPermits    string
	Quotes         string
	SimpleCommands string
}{
	Channels:       "channels",
	LinkPermits:    "link_permits",
	Quotes:         "quotes",
	SimpleCommands: "simple_commands",
}
