// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Channels          string
	Quotes            string
	RepeatedCommands  string
	ScheduledCommands string
	SimpleCommands    string
}{
	Channels:          "channels",
	Quotes:            "quotes",
	RepeatedCommands:  "repeated_commands",
	ScheduledCommands: "scheduled_commands",
	SimpleCommands:    "simple_commands",
}
