// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: active_channels.sql

package dbsql

import (
	"context"
)

const countActiveChannelAssignments = `-- name: CountActiveChannelAssignments :one
SELECT COUNT(*)::integer AS channel_count,
       COUNT(DISTINCT c.bot_name)::integer AS bot_count
FROM channels c
LEFT JOIN twitch_tokens tt ON tt.twitch_id = c.twitch_id
LEFT JOIN moderated_channels m
    ON m.broadcaster_id = c.twitch_id
   AND m.bot_name = c.bot_name
WHERE c.active
  AND ('channel:bot' = ANY(tt.scopes) OR m.id IS NOT NULL)
`

type CountActiveChannelAssignmentsRow struct {
	ChannelCount int32 `json:"channel_count"`
	BotCount     int32 `json:"bot_count"`
}

func (q *Queries) CountActiveChannelAssignments(ctx context.Context) (CountActiveChannelAssignmentsRow, error) {
	row := q.db.QueryRow(ctx, countActiveChannelAssignments)
	var i CountActiveChannelAssignmentsRow
	err := row.Scan(&i.ChannelCount, &i.BotCount)
	return i, err
}

const listActiveChannelAssignments = `-- name: ListActiveChannelAssignments :many
SELECT c.twitch_id, c.bot_name
FROM channels c
LEFT JOIN twitch_tokens tt ON tt.twitch_id = c.twitch_id
LEFT JOIN moderated_channels m
    ON m.broadcaster_id = c.twitch_id
   AND m.bot_name = c.bot_name
WHERE c.active
  AND ('channel:bot' = ANY(tt.scopes) OR m.id IS NOT NULL)
`

type ListActiveChannelAssignmentsRow struct {
	TwitchID int64  `json:"twitch_id"`
	BotName  string `json:"bot_name"`
}

func (q *Queries) ListActiveChannelAssignments(ctx context.Context) ([]ListActiveChannelAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listActiveChannelAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveChannelAssignmentsRow{}
	for rows.Next() {
		var i ListActiveChannelAssignmentsRow
		if err := rows.Scan(&i.TwitchID, &i.BotName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicActiveChannels = `-- name: ListPublicActiveChannels :many
SELECT c.name, c.display_name
FROM channels c
LEFT JOIN twitch_tokens tt ON tt.twitch_id = c.twitch_id
LEFT JOIN moderated_channels m
    ON m.broadcaster_id = c.twitch_id
   AND m.bot_name = c.bot_name
WHERE c.active
  AND ('channel:bot' = ANY(tt.scopes) OR m.id IS NOT NULL)
ORDER BY c.name
`

type ListPublicActiveChannelsRow struct {
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) ListPublicActiveChannels(ctx context.Context) ([]ListPublicActiveChannelsRow, error) {
	rows, err := q.db.Query(ctx, listPublicActiveChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicActiveChannelsRow{}
	for rows.Next() {
		var i ListPublicActiveChannelsRow
		if err := rows.Scan(&i.Name, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
