// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBlockedUser = `-- name: DeleteBlockedUser :exec
DELETE FROM blocked_users WHERE twitch_id = $1
`

func (q *Queries) DeleteBlockedUser(ctx context.Context, twitchID int64) error {
	_, err := q.db.Exec(ctx, deleteBlockedUser, twitchID)
	return err
}

const deleteStaleModeratedChannels = `-- name: DeleteStaleModeratedChannels :exec
DELETE FROM moderated_channels
WHERE bot_name = $1
  AND updated_at < $2
`

type DeleteStaleModeratedChannelsParams struct {
	BotName       string             `json:"bot_name"`
	UpdatedBefore pgtype.Timestamptz `json:"updated_before"`
}

func (q *Queries) DeleteStaleModeratedChannels(ctx context.Context, arg DeleteStaleModeratedChannelsParams) error {
	_, err := q.db.Exec(ctx, deleteStaleModeratedChannels, arg.BotName, arg.UpdatedBefore)
	return err
}

const deleteTwitchTokenByID = `-- name: DeleteTwitchTokenByID :exec
DELETE FROM twitch_tokens WHERE twitch_id = $1
`

func (q *Queries) DeleteTwitchTokenByID(ctx context.Context, twitchID int64) error {
	_, err := q.db.Exec(ctx, deleteTwitchTokenByID, twitchID)
	return err
}

const getTwitchTokenByBotName = `-- name: GetTwitchTokenByBotName :one
SELECT id, created_at, updated_at, twitch_id, bot_name, access_token, token_type, refresh_token, expiry, scopes FROM twitch_tokens WHERE bot_name = $1::text
`

func (q *Queries) GetTwitchTokenByBotName(ctx context.Context, botName string) (TwitchToken, error) {
	row := q.db.QueryRow(ctx, getTwitchTokenByBotName, botName)
	var i TwitchToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwitchID,
		&i.BotName,
		&i.AccessToken,
		&i.TokenType,
		&i.RefreshToken,
		&i.Expiry,
		&i.Scopes,
	)
	return i, err
}

const getTwitchTokenByID = `-- name: GetTwitchTokenByID :one
SELECT id, created_at, updated_at, twitch_id, bot_name, access_token, token_type, refresh_token, expiry, scopes FROM twitch_tokens WHERE twitch_id = $1
`

func (q *Queries) GetTwitchTokenByID(ctx context.Context, twitchID int64) (TwitchToken, error) {
	row := q.db.QueryRow(ctx, getTwitchTokenByID, twitchID)
	var i TwitchToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwitchID,
		&i.BotName,
		&i.AccessToken,
		&i.TokenType,
		&i.RefreshToken,
		&i.Expiry,
		&i.Scopes,
	)
	return i, err
}

const isBlockedUser = `-- name: IsBlockedUser :one
SELECT EXISTS (
    SELECT 1 FROM blocked_users WHERE twitch_id = $1
)
`

func (q *Queries) IsBlockedUser(ctx context.Context, twitchID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isBlockedUser, twitchID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isModeratedChannel = `-- name: IsModeratedChannel :one
SELECT EXISTS (
    SELECT 1
    FROM moderated_channels
    WHERE broadcaster_id = $1
      AND bot_name = $2
)
`

type IsModeratedChannelParams struct {
	BroadcasterID int64  `json:"broadcaster_id"`
	BotName       string `json:"bot_name"`
}

func (q *Queries) IsModeratedChannel(ctx context.Context, arg IsModeratedChannelParams) (bool, error) {
	row := q.db.QueryRow(ctx, isModeratedChannel, arg.BroadcasterID, arg.BotName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBotTwitchTokens = `-- name: ListBotTwitchTokens :many
SELECT id, created_at, updated_at, twitch_id, bot_name, access_token, token_type, refresh_token, expiry, scopes FROM twitch_tokens WHERE bot_name IS NOT NULL ORDER BY bot_name
`

func (q *Queries) ListBotTwitchTokens(ctx context.Context) ([]TwitchToken, error) {
	rows, err := q.db.Query(ctx, listBotTwitchTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TwitchToken{}
	for rows.Next() {
		var i TwitchToken
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TwitchID,
			&i.BotName,
			&i.AccessToken,
			&i.TokenType,
			&i.RefreshToken,
			&i.Expiry,
			&i.Scopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModerationBotTwitchTokens = `-- name: ListModerationBotTwitchTokens :many
SELECT id, created_at, updated_at, twitch_id, bot_name, access_token, token_type, refresh_token, expiry, scopes
FROM twitch_tokens
WHERE bot_name IS NOT NULL
  AND scopes @> ARRAY['user:read:moderated_channels']
ORDER BY bot_name
`

func (q *Queries) ListModerationBotTwitchTokens(ctx context.Context) ([]TwitchToken, error) {
	rows, err := q.db.Query(ctx, listModerationBotTwitchTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TwitchToken{}
	for rows.Next() {
		var i TwitchToken
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TwitchID,
			&i.BotName,
			&i.AccessToken,
			&i.TokenType,
			&i.RefreshToken,
			&i.Expiry,
			&i.Scopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTwitchTokens = `-- name: ListTwitchTokens :many
SELECT id, created_at, updated_at, twitch_id, bot_name, access_token, token_type, refresh_token, expiry, scopes FROM twitch_tokens ORDER BY twitch_id
`

func (q *Queries) ListTwitchTokens(ctx context.Context) ([]TwitchToken, error) {
	rows, err := q.db.Query(ctx, listTwitchTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TwitchToken{}
	for rows.Next() {
		var i TwitchToken
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TwitchID,
			&i.BotName,
			&i.AccessToken,
			&i.TokenType,
			&i.RefreshToken,
			&i.Expiry,
			&i.Scopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockModeratedChannels = `-- name: LockModeratedChannels :exec
LOCK TABLE moderated_channels IN EXCLUSIVE MODE
`

func (q *Queries) LockModeratedChannels(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockModeratedChannels)
	return err
}

const upsertBlockedUser = `-- name: UpsertBlockedUser :exec
INSERT INTO blocked_users (twitch_id)
VALUES ($1)
ON CONFLICT (twitch_id) DO NOTHING
`

func (q *Queries) UpsertBlockedUser(ctx context.Context, twitchID int64) error {
	_, err := q.db.Exec(ctx, upsertBlockedUser, twitchID)
	return err
}

const upsertModeratedChannel = `-- name: UpsertModeratedChannel :exec
INSERT INTO moderated_channels (
    bot_name,
    broadcaster_id,
    broadcaster_login,
    broadcaster_name,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (bot_name, broadcaster_id) DO UPDATE
SET broadcaster_login = excluded.broadcaster_login,
    broadcaster_name = excluded.broadcaster_name,
    updated_at = excluded.updated_at
`

type UpsertModeratedChannelParams struct {
	BotName          string             `json:"bot_name"`
	BroadcasterID    int64              `json:"broadcaster_id"`
	BroadcasterLogin string             `json:"broadcaster_login"`
	BroadcasterName  string             `json:"broadcaster_name"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertModeratedChannel(ctx context.Context, arg UpsertModeratedChannelParams) error {
	_, err := q.db.Exec(ctx, upsertModeratedChannel,
		arg.BotName,
		arg.BroadcasterID,
		arg.BroadcasterLogin,
		arg.BroadcasterName,
		arg.UpdatedAt,
	)
	return err
}

const upsertTwitchToken = `-- name: UpsertTwitchToken :one
INSERT INTO twitch_tokens (
    twitch_id,
    bot_name,
    access_token,
    token_type,
    refresh_token,
    expiry,
    scopes
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::text[]
)
ON CONFLICT (twitch_id) DO UPDATE
SET bot_name = excluded.bot_name,
    access_token = excluded.access_token,
    token_type = excluded.token_type,
    refresh_token = excluded.refresh_token,
    expiry = excluded.expiry,
    scopes = excluded.scopes,
    updated_at = statement_timestamp()
RETURNING id, created_at, updated_at, twitch_id, bot_name, access_token, token_type, refresh_token, expiry, scopes
`

type UpsertTwitchTokenParams struct {
	TwitchID     int64              `json:"twitch_id"`
	BotName      pgtype.Text        `json:"bot_name"`
	AccessToken  string             `json:"access_token"`
	TokenType    string             `json:"token_type"`
	RefreshToken string             `json:"refresh_token"`
	Expiry       pgtype.Timestamptz `json:"expiry"`
	Scopes       []string           `json:"scopes"`
}

func (q *Queries) UpsertTwitchToken(ctx context.Context, arg UpsertTwitchTokenParams) (TwitchToken, error) {
	row := q.db.QueryRow(ctx, upsertTwitchToken,
		arg.TwitchID,
		arg.BotName,
		arg.AccessToken,
		arg.TokenType,
		arg.RefreshToken,
		arg.Expiry,
		arg.Scopes,
	)
	var i TwitchToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwitchID,
		&i.BotName,
		&i.AccessToken,
		&i.TokenType,
		&i.RefreshToken,
		&i.Expiry,
		&i.Scopes,
	)
	return i, err
}

const upsertTwitchTokenPreservingMetadata = `-- name: UpsertTwitchTokenPreservingMetadata :one
INSERT INTO twitch_tokens (
    twitch_id,
    access_token,
    token_type,
    refresh_token,
    expiry
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (twitch_id) DO UPDATE
SET access_token = excluded.access_token,
    token_type = excluded.token_type,
    refresh_token = excluded.refresh_token,
    expiry = excluded.expiry,
    updated_at = statement_timestamp()
RETURNING id, created_at, updated_at, twitch_id, bot_name, access_token, token_type, refresh_token, expiry, scopes
`

type UpsertTwitchTokenPreservingMetadataParams struct {
	TwitchID     int64              `json:"twitch_id"`
	AccessToken  string             `json:"access_token"`
	TokenType    string             `json:"token_type"`
	RefreshToken string             `json:"refresh_token"`
	Expiry       pgtype.Timestamptz `json:"expiry"`
}

func (q *Queries) UpsertTwitchTokenPreservingMetadata(ctx context.Context, arg UpsertTwitchTokenPreservingMetadataParams) (TwitchToken, error) {
	row := q.db.QueryRow(ctx, upsertTwitchTokenPreservingMetadata,
		arg.TwitchID,
		arg.AccessToken,
		arg.TokenType,
		arg.RefreshToken,
		arg.Expiry,
	)
	var i TwitchToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwitchID,
		&i.BotName,
		&i.AccessToken,
		&i.TokenType,
		&i.RefreshToken,
		&i.Expiry,
		&i.Scopes,
	)
	return i, err
}
