// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chatqueue.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const chatQueueClaim = `-- name: ChatQueueClaim :one
SELECT
    q.message_id,
    q.broadcaster_login,
    q.message_timestamp,
    q.enqueued_at,
    q.payload
FROM chat_message_queue AS q
JOIN chat_message_queue_keys AS k USING (broadcaster_login)
WHERE q.completed_at IS NULL
  AND q.failed_at IS NULL
  AND (q.lease_until IS NULL OR q.lease_until <= NOW())
  AND (k.lease_until IS NULL OR k.lease_until <= NOW())
ORDER BY q.enqueued_at, q.message_id
FOR UPDATE OF q, k SKIP LOCKED
LIMIT 1
`

type ChatQueueClaimRow struct {
	MessageID        string             `json:"message_id"`
	BroadcasterLogin string             `json:"broadcaster_login"`
	MessageTimestamp pgtype.Timestamptz `json:"message_timestamp"`
	EnqueuedAt       pgtype.Timestamptz `json:"enqueued_at"`
	Payload          []byte             `json:"payload"`
}

func (q *Queries) ChatQueueClaim(ctx context.Context) (ChatQueueClaimRow, error) {
	row := q.db.QueryRow(ctx, chatQueueClaim)
	var i ChatQueueClaimRow
	err := row.Scan(
		&i.MessageID,
		&i.BroadcasterLogin,
		&i.MessageTimestamp,
		&i.EnqueuedAt,
		&i.Payload,
	)
	return i, err
}

const chatQueueComplete = `-- name: ChatQueueComplete :execrows
UPDATE chat_message_queue
SET completed_at = NOW(),
    lease_token = NULL,
    lease_until = NULL
WHERE message_id = $1
  AND lease_token = $2::text
  AND completed_at IS NULL
  AND failed_at IS NULL
`

type ChatQueueCompleteParams struct {
	MessageID  string `json:"message_id"`
	LeaseToken string `json:"lease_token"`
}

func (q *Queries) ChatQueueComplete(ctx context.Context, arg ChatQueueCompleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, chatQueueComplete, arg.MessageID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const chatQueueDeleteCompleted = `-- name: ChatQueueDeleteCompleted :execrows
WITH doomed AS (
    SELECT completed.message_id
    FROM chat_message_queue AS completed
    WHERE completed.completed_at <= $1::timestamptz
    ORDER BY completed.completed_at, completed.message_id
    FOR UPDATE SKIP LOCKED
    LIMIT $2::bigint
)
DELETE FROM chat_message_queue AS q
USING doomed
WHERE q.message_id = doomed.message_id
`

type ChatQueueDeleteCompletedParams struct {
	Cutoff     pgtype.Timestamptz `json:"cutoff"`
	BatchLimit int64              `json:"batch_limit"`
}

func (q *Queries) ChatQueueDeleteCompleted(ctx context.Context, arg ChatQueueDeleteCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, chatQueueDeleteCompleted, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const chatQueueDeleteFailed = `-- name: ChatQueueDeleteFailed :execrows
WITH doomed AS (
    SELECT failed.message_id
    FROM chat_message_queue AS failed
    WHERE failed.failed_at <= $1::timestamptz
    ORDER BY failed.failed_at, failed.message_id
    FOR UPDATE SKIP LOCKED
    LIMIT $2::bigint
)
DELETE FROM chat_message_queue AS q
USING doomed
WHERE q.message_id = doomed.message_id
`

type ChatQueueDeleteFailedParams struct {
	Cutoff     pgtype.Timestamptz `json:"cutoff"`
	BatchLimit int64              `json:"batch_limit"`
}

func (q *Queries) ChatQueueDeleteFailed(ctx context.Context, arg ChatQueueDeleteFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, chatQueueDeleteFailed, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const chatQueueDeleteStale = `-- name: ChatQueueDeleteStale :execrows
WITH doomed AS (
    SELECT stale.message_id
    FROM chat_message_queue AS stale
    WHERE stale.message_timestamp <= $1
      AND stale.completed_at IS NULL
      AND stale.failed_at IS NULL
      AND (stale.lease_until IS NULL OR stale.lease_until <= NOW())
    ORDER BY stale.message_timestamp, stale.message_id
    FOR UPDATE SKIP LOCKED
    LIMIT $2::bigint
)
DELETE FROM chat_message_queue AS q
USING doomed
WHERE q.message_id = doomed.message_id
`

type ChatQueueDeleteStaleParams struct {
	Cutoff     pgtype.Timestamptz `json:"cutoff"`
	BatchLimit int64              `json:"batch_limit"`
}

func (q *Queries) ChatQueueDeleteStale(ctx context.Context, arg ChatQueueDeleteStaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, chatQueueDeleteStale, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const chatQueueEnqueue = `-- name: ChatQueueEnqueue :execrows
INSERT INTO chat_message_queue (
    message_id,
    broadcaster_login,
    message_timestamp,
    enqueued_at,
    payload
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (message_id) DO NOTHING
`

type ChatQueueEnqueueParams struct {
	MessageID        string             `json:"message_id"`
	BroadcasterLogin string             `json:"broadcaster_login"`
	MessageTimestamp pgtype.Timestamptz `json:"message_timestamp"`
	EnqueuedAt       pgtype.Timestamptz `json:"enqueued_at"`
	Payload          []byte             `json:"payload"`
}

func (q *Queries) ChatQueueEnqueue(ctx context.Context, arg ChatQueueEnqueueParams) (int64, error) {
	result, err := q.db.Exec(ctx, chatQueueEnqueue,
		arg.MessageID,
		arg.BroadcasterLogin,
		arg.MessageTimestamp,
		arg.EnqueuedAt,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const chatQueueEnsureKey = `-- name: ChatQueueEnsureKey :exec
INSERT INTO chat_message_queue_keys (broadcaster_login)
VALUES ($1)
ON CONFLICT (broadcaster_login) DO NOTHING
`

func (q *Queries) ChatQueueEnsureKey(ctx context.Context, broadcasterLogin string) error {
	_, err := q.db.Exec(ctx, chatQueueEnsureKey, broadcasterLogin)
	return err
}

const chatQueueFail = `-- name: ChatQueueFail :execrows
UPDATE chat_message_queue
SET failed_at = NOW(),
    last_error = $1::text,
    lease_token = NULL,
    lease_until = NULL
WHERE message_id = $2
  AND lease_token = $3::text
`

type ChatQueueFailParams struct {
	LastError  string `json:"last_error"`
	MessageID  string `json:"message_id"`
	LeaseToken string `json:"lease_token"`
}

func (q *Queries) ChatQueueFail(ctx context.Context, arg ChatQueueFailParams) (int64, error) {
	result, err := q.db.Exec(ctx, chatQueueFail, arg.LastError, arg.MessageID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const chatQueueLeaseKey = `-- name: ChatQueueLeaseKey :one
UPDATE chat_message_queue_keys
SET lease_token = $1::text,
    lease_until = NOW() + ($2::bigint * INTERVAL '1 microsecond')
WHERE broadcaster_login = $3
RETURNING COALESCE(lease_until, NOW())::timestamptz AS lease_until
`

type ChatQueueLeaseKeyParams struct {
	LeaseToken        string `json:"lease_token"`
	LeaseMicroseconds int64  `json:"lease_microseconds"`
	BroadcasterLogin  string `json:"broadcaster_login"`
}

func (q *Queries) ChatQueueLeaseKey(ctx context.Context, arg ChatQueueLeaseKeyParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, chatQueueLeaseKey, arg.LeaseToken, arg.LeaseMicroseconds, arg.BroadcasterLogin)
	var lease_until pgtype.Timestamptz
	err := row.Scan(&lease_until)
	return lease_until, err
}

const chatQueueLeaseMessage = `-- name: ChatQueueLeaseMessage :exec
UPDATE chat_message_queue
SET lease_token = $1::text,
    lease_until = $2::timestamptz
WHERE message_id = $3
`

type ChatQueueLeaseMessageParams struct {
	LeaseToken string             `json:"lease_token"`
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
	MessageID  string             `json:"message_id"`
}

func (q *Queries) ChatQueueLeaseMessage(ctx context.Context, arg ChatQueueLeaseMessageParams) error {
	_, err := q.db.Exec(ctx, chatQueueLeaseMessage, arg.LeaseToken, arg.LeaseUntil, arg.MessageID)
	return err
}

const chatQueueNotify = `-- name: ChatQueueNotify :exec
SELECT pg_notify($1, '')
`

func (q *Queries) ChatQueueNotify(ctx context.Context, channel string) error {
	_, err := q.db.Exec(ctx, chatQueueNotify, channel)
	return err
}

const chatQueueReleaseKey = `-- name: ChatQueueReleaseKey :exec
UPDATE chat_message_queue_keys
SET lease_token = NULL,
    lease_until = NULL
WHERE broadcaster_login = $1
  AND lease_token = $2::text
`

type ChatQueueReleaseKeyParams struct {
	BroadcasterLogin string `json:"broadcaster_login"`
	LeaseToken       string `json:"lease_token"`
}

func (q *Queries) ChatQueueReleaseKey(ctx context.Context, arg ChatQueueReleaseKeyParams) error {
	_, err := q.db.Exec(ctx, chatQueueReleaseKey, arg.BroadcasterLogin, arg.LeaseToken)
	return err
}
