// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config_import.sql

package dbsql

import (
	"context"
)

const insertFixtureChannel = `-- name: InsertFixtureChannel :one
INSERT INTO channels
SELECT (jsonb_populate_record(NULL::channels, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertFixtureChannel(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertFixtureChannel, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertFixtureCommandInfo = `-- name: InsertFixtureCommandInfo :one
INSERT INTO command_infos
SELECT (jsonb_populate_record(NULL::command_infos, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertFixtureCommandInfo(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertFixtureCommandInfo, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertFixtureCustomCommand = `-- name: InsertFixtureCustomCommand :one
INSERT INTO custom_commands
SELECT (jsonb_populate_record(NULL::custom_commands, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertFixtureCustomCommand(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertFixtureCustomCommand, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertFixtureRepeatedCommand = `-- name: InsertFixtureRepeatedCommand :one
INSERT INTO repeated_commands
SELECT (jsonb_populate_record(NULL::repeated_commands, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertFixtureRepeatedCommand(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertFixtureRepeatedCommand, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertFixtureScheduledCommand = `-- name: InsertFixtureScheduledCommand :one
INSERT INTO scheduled_commands
SELECT (jsonb_populate_record(NULL::scheduled_commands, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertFixtureScheduledCommand(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertFixtureScheduledCommand, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImportedAutoreply = `-- name: InsertImportedAutoreply :one
INSERT INTO autoreplies OVERRIDING USER VALUE
SELECT (jsonb_populate_record(NULL::autoreplies, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertImportedAutoreply(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertImportedAutoreply, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImportedChannel = `-- name: InsertImportedChannel :one
INSERT INTO channels OVERRIDING USER VALUE
SELECT (jsonb_populate_record(NULL::channels, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertImportedChannel(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertImportedChannel, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImportedCommandInfo = `-- name: InsertImportedCommandInfo :one
INSERT INTO command_infos OVERRIDING USER VALUE
SELECT (jsonb_populate_record(NULL::command_infos, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertImportedCommandInfo(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertImportedCommandInfo, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImportedCommandList = `-- name: InsertImportedCommandList :one
INSERT INTO command_lists OVERRIDING USER VALUE
SELECT (jsonb_populate_record(NULL::command_lists, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertImportedCommandList(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertImportedCommandList, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImportedCustomCommand = `-- name: InsertImportedCustomCommand :one
INSERT INTO custom_commands OVERRIDING USER VALUE
SELECT (jsonb_populate_record(NULL::custom_commands, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertImportedCustomCommand(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertImportedCustomCommand, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImportedQuote = `-- name: InsertImportedQuote :one
INSERT INTO quotes OVERRIDING USER VALUE
SELECT (jsonb_populate_record(NULL::quotes, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertImportedQuote(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertImportedQuote, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImportedRepeatedCommand = `-- name: InsertImportedRepeatedCommand :one
INSERT INTO repeated_commands OVERRIDING USER VALUE
SELECT (jsonb_populate_record(NULL::repeated_commands, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertImportedRepeatedCommand(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertImportedRepeatedCommand, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImportedScheduledCommand = `-- name: InsertImportedScheduledCommand :one
INSERT INTO scheduled_commands OVERRIDING USER VALUE
SELECT (jsonb_populate_record(NULL::scheduled_commands, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertImportedScheduledCommand(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertImportedScheduledCommand, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImportedVariable = `-- name: InsertImportedVariable :one
INSERT INTO variables OVERRIDING USER VALUE
SELECT (jsonb_populate_record(NULL::variables, $1::jsonb)).*
RETURNING id
`

func (q *Queries) InsertImportedVariable(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertImportedVariable, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}
