// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import (
	"context"

	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type IndexPage struct {
	BasePage
}

func (p *IndexPage) StreamPageTitle(qw422016 *qt422016.Writer, ctx context.Context) {
	qw422016.N().S(`
    HortBot
`)
}

func (p *IndexPage) WritePageTitle(qq422016 qtio422016.Writer, ctx context.Context) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamPageTitle(qw422016, ctx)
	qt422016.ReleaseWriter(qw422016)
}

func (p *IndexPage) PageTitle(ctx context.Context) string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WritePageTitle(qb422016, ctx)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *IndexPage) StreamPageMeta(qw422016 *qt422016.Writer, ctx context.Context) {
	qw422016.N().S(`
`)
}

func (p *IndexPage) WritePageMeta(qq422016 qtio422016.Writer, ctx context.Context) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamPageMeta(qw422016, ctx)
	qt422016.ReleaseWriter(qw422016)
}

func (p *IndexPage) PageMeta(ctx context.Context) string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WritePageMeta(qb422016, ctx)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *IndexPage) StreamPageBody(qw422016 *qt422016.Writer, ctx context.Context) {
	qw422016.N().S(`
    This is the home page.
`)
}

func (p *IndexPage) WritePageBody(qq422016 qtio422016.Writer, ctx context.Context) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamPageBody(qw422016, ctx)
	qt422016.ReleaseWriter(qw422016)
}

func (p *IndexPage) PageBody(ctx context.Context) string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WritePageBody(qb422016, ctx)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *IndexPage) StreamPageScripts(qw422016 *qt422016.Writer, ctx context.Context) {
	qw422016.N().S(`
`)
}

func (p *IndexPage) WritePageScripts(qq422016 qtio422016.Writer, ctx context.Context) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamPageScripts(qw422016, ctx)
	qt422016.ReleaseWriter(qw422016)
}

func (p *IndexPage) PageScripts(ctx context.Context) string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WritePageScripts(qb422016, ctx)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
