// Code generated by qtc from "sidebar_scripts.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func streamsidebarStyle(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<style>
html {
    overflow-y: hidden;
}

.is-sidebar-menu {
    padding: 2.5rem;
    background: #444444;
    width: 20em;
    overflow-y: auto;
    border-right: 1px solid #777777;
    margin-top: 0.75rem;
}

.columns.is-fullheight {
    min-height: calc(100vh - ( 4rem - .75rem ) );
    max-height: calc(100vh - ( 4rem - .75rem ) );
    height: calc(100vh - ( 4rem - .75rem ) );
    display: flex;
    flex-direction: row;
    justify-content: stretch;
    margin-bottom: 0;
}
.columns.is-fullheight .column {
    overflow-y: auto;
}

.is-main-content {
    margin-top: 0.75rem;
    margin-right: 0.75rem;
    padding: 2.5rem;
}

ol {
    list-style-position: inside;
}
</style>
`)
}

func writesidebarStyle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	streamsidebarStyle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func sidebarStyle() string {
	qb422016 := qt422016.AcquireByteBuffer()
	writesidebarStyle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
